functions_csv = "data/exking_functions.csv"
build_target = "exking"

[decomp_me]
compiler_name = "clang-14.0.0"
default_compile_flags = "-x c++ -O3 -g2 -std=c++1z -fno-rtti -fno-exceptions -Wall -Wextra -fno-strict-aliasing"